### PR TITLE
OR-1159 make nightly github action fixing push branch

### PR DESCRIPTION
**Pull request by boohyung**
make nightly github action fixing push branch
* fix 'main' to 'feature/native-token'

### CODE REVIEW

**Review by rlgns98kr — APPROVED** [review]
Thank you!

**Comment by rlgns98kr** [comment]
In fact, this PR have to merge first. I think you can commit anything for github action directly on `feature/fee_token` 🙇🏻‍♂️

**Comment by boohyung** [comment]
> @boohyung In fact, this PR had to merge first. I think you can commit anything for github action directly on `feature/fee_token` 🙇🏻‍♂️

Oh I missed it. Thanks for the advice. Let me test it as you said.

**Comment by rlgns98kr** [comment]
> > @boohyung In fact, this PR had to merge first. I think you can commit anything for github action directly on `feature/fee_token` 🙇🏻‍♂️
> 
> Oh I missed it. Thanks for the advice. Let me test it as you said.

Thank you very much! 🙇🏻‍♂️

**Pull request merged**
